
id = "TitleAPI-CPATCH"
name = "TitleAPI-CPATCH"
description = "Patches some stuff for TitleAPI"
version = "1.0.0"
homepage = ""
author = "IamKikin"

icon = "icon.png"
readme = "README.md"

[project]
csharp = "./TitleAPI-CPATCH/TitleAPI-CPATCH.csproj"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.13"
